import { describe, it, expect, vi, beforeEach } from 'vitest';
import fc from 'fast-check';

/**
 * Property 6: Option proposal structural validity
 *
 * For any OptionProposal generated by the AI Architect, the proposal SHALL contain
 * between 2 and 5 options (inclusive). Each option SHALL have: a summary of at most
 * 200 characters, at least 2 benefits, at least 2 risks, and a complexity value in
 * the set {Low, Medium, High}. The accompanying TradeoffTable SHALL have exactly one
 * row per option and one column per stated constraint.
 *
 * **Validates: Requirements 3.2, 3.3**
 */

// Mock the Bedrock service
const mockInvokeClaudeModel = vi.hoisted(() => vi.fn());

vi.mock('@/services/bedrock', () => ({
  invokeClaudeModel: mockInvokeClaudeModel,
}));

import { proposeOptions } from '@/lib/ai-architect';
import type { Message, MessageId, ThreadId, OptionProposal } from '@/types/domain';

// =============================================================================
// Generators
// =============================================================================

const complexityArb = fc.constantFrom('Low', 'Medium', 'High');

const optionArb = fc.record({
  summary: fc.string({ minLength: 1, maxLength: 200 }).filter((s) => s.trim().length > 0),
  benefits: fc.array(fc.string({ minLength: 1, maxLength: 100 }).filter((s) => s.trim().length > 0), { minLength: 2, maxLength: 5 }),
  risks: fc.array(fc.string({ minLength: 1, maxLength: 100 }).filter((s) => s.trim().length > 0), { minLength: 2, maxLength: 5 }),
  complexity: complexityArb,
});

const constraintArb = fc.string({ minLength: 1, maxLength: 80 }).filter((s) => s.trim().length > 0);

/**
 * Generates a valid OptionProposal with 2-5 options and a consistent tradeoff table.
 * The tradeoff table's options array length matches the options count, and
 * the ratings matrix has one row per option with one column per constraint.
 */
const optionProposalArb = fc
  .tuple(
    fc.array(optionArb, { minLength: 2, maxLength: 5 }),
    fc.array(constraintArb, { minLength: 1, maxLength: 6 }),
  )
  .map(([options, constraints]) => {
    const optionNames = options.map((_, i) => `Option ${String.fromCharCode(65 + i)}`);
    const ratings = options.map(() =>
      constraints.map(() => fc.sample(fc.constantFrom('Good', 'Fair', 'Poor', 'Excellent', 'Moderate'), 1)[0]),
    );
    return {
      options,
      tradeoffTable: {
        options: optionNames,
        constraints,
        ratings,
      },
    };
  });

/**
 * Generates a simple Message array for use as input to proposeOptions.
 */
const messagesArb = fc.array(
  fc.record({
    messageId: fc.uuid().map((id) => id as MessageId),
    threadId: fc.uuid().map((id) => id as ThreadId),
    sender: fc.constantFrom('user-1', 'ai_architect'),
    content: fc.string({ minLength: 1, maxLength: 300 }),
    createdAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-01-01') }).map((d) => d.toISOString()),
  }),
  { minLength: 1, maxLength: 5 },
);

const constraintsInputArb = fc.array(fc.string({ minLength: 1, maxLength: 100 }), { minLength: 0, maxLength: 5 });

// =============================================================================
// Tests
// =============================================================================

describe('Property 6: Option proposal structural validity', () => {
  beforeEach(() => {
    mockInvokeClaudeModel.mockReset();
  });

  it('for any valid OptionProposal returned by Bedrock, proposeOptions validates and returns a proposal with 2-5 options, each with summary ≤200 chars, ≥2 benefits, ≥2 risks, complexity in {Low, Medium, High}, and tradeoff table with one row per option and ≥1 constraint', async () => {
    await fc.assert(
      fc.asyncProperty(
        optionProposalArb,
        messagesArb,
        constraintsInputArb,
        async (proposal, messages, constraints) => {
          // Mock Bedrock to return the generated proposal as JSON
          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(proposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints,
            priorDecisions: [],
          });

          // proposeOptions should succeed since the proposal is structurally valid
          expect(result.ok).toBe(true);
          if (!result.ok) return;

          const validated: OptionProposal = result.value;

          // 1. Options array has 2-5 items
          expect(validated.options.length).toBeGreaterThanOrEqual(2);
          expect(validated.options.length).toBeLessThanOrEqual(5);

          // 2. Each option has valid structure
          for (const option of validated.options) {
            // Summary ≤200 characters
            expect(option.summary.length).toBeLessThanOrEqual(200);
            expect(option.summary.length).toBeGreaterThanOrEqual(1);

            // ≥2 benefits
            expect(option.benefits.length).toBeGreaterThanOrEqual(2);
            for (const benefit of option.benefits) {
              expect(benefit.length).toBeGreaterThanOrEqual(1);
            }

            // ≥2 risks
            expect(option.risks.length).toBeGreaterThanOrEqual(2);
            for (const risk of option.risks) {
              expect(risk.length).toBeGreaterThanOrEqual(1);
            }

            // Complexity in {Low, Medium, High}
            expect(['Low', 'Medium', 'High']).toContain(option.complexity);
          }

          // 3. TradeoffTable structure
          const table = validated.tradeoffTable;

          // One row per option (options array in table matches options count)
          expect(table.options.length).toBe(validated.options.length);

          // At least 1 constraint column
          expect(table.constraints.length).toBeGreaterThanOrEqual(1);

          // Ratings has one row per option
          expect(table.ratings.length).toBe(validated.options.length);

          // Each rating row has one column per constraint
          for (const row of table.ratings) {
            expect(row.length).toBe(table.constraints.length);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('proposals with fewer than 2 options are rejected by validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        optionArb,
        messagesArb,
        async (singleOption, messages) => {
          // Generate an invalid proposal with only 1 option
          const invalidProposal = {
            options: [singleOption],
            tradeoffTable: {
              options: ['Option A'],
              constraints: ['constraint-1'],
              ratings: [['Good']],
            },
          };

          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(invalidProposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints: ['some constraint'],
            priorDecisions: [],
          });

          // Should fail validation (fewer than 2 options)
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('RESPONSE_VALIDATION_FAILURE');
          }
        },
      ),
      { numRuns: 50 },
    );
  });

  it('proposals with more than 5 options are rejected by validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(optionArb, { minLength: 6, maxLength: 8 }),
        messagesArb,
        async (options, messages) => {
          const optionNames = options.map((_, i) => `Option ${i + 1}`);
          const invalidProposal = {
            options,
            tradeoffTable: {
              options: optionNames,
              constraints: ['constraint-1'],
              ratings: options.map(() => ['Good']),
            },
          };

          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(invalidProposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints: ['some constraint'],
            priorDecisions: [],
          });

          // Should fail validation (more than 5 options)
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('RESPONSE_VALIDATION_FAILURE');
          }
        },
      ),
      { numRuns: 50 },
    );
  });

  it('proposals with summary exceeding 200 chars are rejected by validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 201, maxLength: 400 }),
        messagesArb,
        async (longSummary, messages) => {
          const invalidProposal = {
            options: [
              { summary: longSummary, benefits: ['b1', 'b2'], risks: ['r1', 'r2'], complexity: 'Low' },
              { summary: 'Valid short summary', benefits: ['b1', 'b2'], risks: ['r1', 'r2'], complexity: 'High' },
            ],
            tradeoffTable: {
              options: ['Option A', 'Option B'],
              constraints: ['constraint-1'],
              ratings: [['Good'], ['Fair']],
            },
          };

          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(invalidProposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints: ['constraint-1'],
            priorDecisions: [],
          });

          // Should fail validation (summary > 200 chars)
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('RESPONSE_VALIDATION_FAILURE');
          }
        },
      ),
      { numRuns: 50 },
    );
  });

  it('proposals with fewer than 2 benefits or risks are rejected by validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        messagesArb,
        fc.constantFrom('benefits', 'risks'),
        async (messages, field) => {
          const option1 = {
            summary: 'Valid summary',
            benefits: field === 'benefits' ? ['only-one'] : ['b1', 'b2'],
            risks: field === 'risks' ? ['only-one'] : ['r1', 'r2'],
            complexity: 'Medium',
          };
          const option2 = {
            summary: 'Another valid summary',
            benefits: ['b1', 'b2'],
            risks: ['r1', 'r2'],
            complexity: 'High',
          };

          const invalidProposal = {
            options: [option1, option2],
            tradeoffTable: {
              options: ['Option A', 'Option B'],
              constraints: ['constraint-1'],
              ratings: [['Good'], ['Fair']],
            },
          };

          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(invalidProposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints: ['constraint-1'],
            priorDecisions: [],
          });

          // Should fail validation (fewer than 2 benefits or risks)
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('RESPONSE_VALIDATION_FAILURE');
          }
        },
      ),
      { numRuns: 50 },
    );
  });

  it('proposals with invalid complexity values are rejected by validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        messagesArb,
        fc.string({ minLength: 1, maxLength: 20 }).filter((s) => !['Low', 'Medium', 'High'].includes(s)),
        async (messages, invalidComplexity) => {
          const invalidProposal = {
            options: [
              { summary: 'Option A', benefits: ['b1', 'b2'], risks: ['r1', 'r2'], complexity: invalidComplexity },
              { summary: 'Option B', benefits: ['b1', 'b2'], risks: ['r1', 'r2'], complexity: 'High' },
            ],
            tradeoffTable: {
              options: ['Option A', 'Option B'],
              constraints: ['constraint-1'],
              ratings: [['Good'], ['Fair']],
            },
          };

          mockInvokeClaudeModel.mockResolvedValueOnce({
            ok: true,
            value: JSON.stringify(invalidProposal),
          });

          const result = await proposeOptions({
            messages: messages as Message[],
            constraints: ['constraint-1'],
            priorDecisions: [],
          });

          // Should fail validation (invalid complexity)
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('RESPONSE_VALIDATION_FAILURE');
          }
        },
      ),
      { numRuns: 50 },
    );
  });
});



// =============================================================================
// Property 24: Tradeoff regeneration tracks changes
// =============================================================================

/**
 * Property 24: Tradeoff regeneration tracks changes
 *
 * For any regeneration triggered by new constraints, the returned `TradeoffChange[]`
 * contains one entry per changed field, each identifying option, field, previous value,
 * new value, and reason.
 *
 * **Validates: Requirements 3.4**
 */

import { regenerateTradeoffTable } from '@/lib/ai-architect';
import type { TradeoffTable, TradeoffChange } from '@/types/domain';

// Generators for Property 24
const VALID_CHANGE_FIELDS = ['summary', 'benefits', 'risks', 'complexity', 'tradeoff_rating'] as const;

/** Generator for a single TradeoffChange with valid structure */
const tradeoffChangeArb = fc
  .record({
    optionId: fc.string({ minLength: 1, maxLength: 30 }),
    field: fc.constantFrom(...VALID_CHANGE_FIELDS),
    previousValue: fc.string({ minLength: 1, maxLength: 100 }),
    newValue: fc.string({ minLength: 1, maxLength: 100 }),
    reason: fc.string({ minLength: 1, maxLength: 200 }),
  })
  .chain((change) => {
    if (change.field === 'tradeoff_rating') {
      return fc.string({ minLength: 1, maxLength: 50 }).map((constraintName) => ({
        ...change,
        constraintName,
      }));
    }
    return fc.constant(change);
  });

/** Generator for a valid TradeoffTable */
const tradeoffTableArb = fc
  .record({
    options: fc.array(fc.string({ minLength: 1, maxLength: 30 }), { minLength: 2, maxLength: 5 }),
    constraints: fc.array(fc.string({ minLength: 1, maxLength: 50 }), { minLength: 1, maxLength: 5 }),
  })
  .map(({ options, constraints }) => ({
    options,
    constraints,
    ratings: options.map(() => constraints.map(() => 'Good')),
  }));

/** Generator for new constraints to add */
const newConstraintsArb = fc.array(fc.string({ minLength: 1, maxLength: 80 }), {
  minLength: 1,
  maxLength: 3,
});

/** Generator for a minimal valid Message (reusing the Message type) */
const messageArbP24: fc.Arbitrary<Message> = fc.record({
  messageId: fc.uuid().map((id) => id as MessageId),
  threadId: fc.uuid().map((id) => id as ThreadId),
  sender: fc.constantFrom('user-1', 'user-2', 'ai_architect'),
  content: fc.string({ minLength: 1, maxLength: 200 }),
  createdAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-01-01') }).map((d) => d.toISOString()),
});

describe('Property 24: Tradeoff regeneration tracks changes', () => {
  beforeEach(() => {
    mockInvokeClaudeModel.mockReset();
  });

  it('for any regeneration, each TradeoffChange has non-empty optionId, valid field, previousValue, newValue, and non-empty reason', async () => {
    await fc.assert(
      fc.asyncProperty(
        tradeoffTableArb,
        newConstraintsArb,
        fc.array(tradeoffChangeArb, { minLength: 1, maxLength: 5 }),
        fc.array(messageArbP24, { minLength: 1, maxLength: 3 }),
        async (previousTable, newConstraints, generatedChanges, messages) => {
          mockInvokeClaudeModel.mockReset();

          const regeneratedTable: TradeoffTable = {
            options: previousTable.options,
            constraints: [...previousTable.constraints, ...newConstraints],
            ratings: previousTable.options.map(() =>
              [...previousTable.constraints, ...newConstraints].map(() => 'Updated'),
            ),
          };

          const mockResponse = JSON.stringify({
            table: regeneratedTable,
            changes: generatedChanges,
          });

          mockInvokeClaudeModel.mockResolvedValueOnce({ ok: true, value: mockResponse });

          const result = await regenerateTradeoffTable({
            previousTable,
            newConstraints,
            messages,
          });

          expect(result.ok).toBe(true);
          if (!result.ok) return;

          // Each change has valid structure
          for (const change of result.value.changes) {
            expect(change.optionId.length).toBeGreaterThan(0);
            expect(VALID_CHANGE_FIELDS).toContain(change.field);
            expect(typeof change.previousValue).toBe('string');
            expect(typeof change.newValue).toBe('string');
            expect(change.reason.length).toBeGreaterThan(0);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('for tradeoff_rating field changes, constraintName is present', async () => {
    await fc.assert(
      fc.asyncProperty(
        tradeoffTableArb,
        newConstraintsArb,
        fc.array(messageArbP24, { minLength: 1, maxLength: 3 }),
        async (previousTable, newConstraints, messages) => {
          mockInvokeClaudeModel.mockReset();

          // Generate changes that include a tradeoff_rating change
          const tradeoffRatingChange: TradeoffChange = {
            optionId: previousTable.options[0],
            field: 'tradeoff_rating',
            constraintName: newConstraints[0],
            previousValue: 'Good',
            newValue: 'Poor',
            reason: 'New constraint impacts this option negatively',
          };

          const regeneratedTable: TradeoffTable = {
            options: previousTable.options,
            constraints: [...previousTable.constraints, ...newConstraints],
            ratings: previousTable.options.map(() =>
              [...previousTable.constraints, ...newConstraints].map(() => 'Updated'),
            ),
          };

          const mockResponse = JSON.stringify({
            table: regeneratedTable,
            changes: [tradeoffRatingChange],
          });

          mockInvokeClaudeModel.mockResolvedValueOnce({ ok: true, value: mockResponse });

          const result = await regenerateTradeoffTable({
            previousTable,
            newConstraints,
            messages,
          });

          expect(result.ok).toBe(true);
          if (!result.ok) return;

          // For tradeoff_rating changes, constraintName should be present
          const ratingChanges = result.value.changes.filter((c) => c.field === 'tradeoff_rating');
          for (const change of ratingChanges) {
            expect(change.constraintName).toBeDefined();
            expect(change.constraintName!.length).toBeGreaterThan(0);
          }
        },
      ),
      { numRuns: 100 },
    );
  });

  it('changes array length matches the number of changed fields returned by the AI', async () => {
    await fc.assert(
      fc.asyncProperty(
        tradeoffTableArb,
        newConstraintsArb,
        fc.array(tradeoffChangeArb, { minLength: 0, maxLength: 8 }),
        fc.array(messageArbP24, { minLength: 1, maxLength: 3 }),
        async (previousTable, newConstraints, generatedChanges, messages) => {
          mockInvokeClaudeModel.mockReset();

          const regeneratedTable: TradeoffTable = {
            options: previousTable.options,
            constraints: [...previousTable.constraints, ...newConstraints],
            ratings: previousTable.options.map(() =>
              [...previousTable.constraints, ...newConstraints].map(() => 'Updated'),
            ),
          };

          const mockResponse = JSON.stringify({
            table: regeneratedTable,
            changes: generatedChanges,
          });

          mockInvokeClaudeModel.mockResolvedValueOnce({ ok: true, value: mockResponse });

          const result = await regenerateTradeoffTable({
            previousTable,
            newConstraints,
            messages,
          });

          expect(result.ok).toBe(true);
          if (!result.ok) return;

          // The number of returned changes should match what the AI returned
          expect(result.value.changes.length).toBe(generatedChanges.length);
        },
      ),
      { numRuns: 100 },
    );
  });
});

// =============================================================================
// Property 28: Single-option fallback with relaxation suggestions
// =============================================================================

/**
 * Property 28: Single-option fallback with relaxation suggestions
 *
 * When constraints produce only one viable option, `proposeOptionsWithFallback`
 * returns `single_option` with valid option structure and non-empty `relaxationSuggestions`.
 *
 * **Validates: Requirements 3.5**
 */

import { proposeOptionsWithFallback } from '@/lib/ai-architect';

// Generators for Property 28

/** Generates a valid single architecture option with constrained fields. */
const singleOptionArb = fc.record({
  summary: fc.string({ minLength: 1, maxLength: 200 }).filter((s) => s.trim().length > 0),
  benefits: fc.array(fc.string({ minLength: 1, maxLength: 100 }).filter((s) => s.trim().length > 0), { minLength: 2, maxLength: 5 }),
  risks: fc.array(fc.string({ minLength: 1, maxLength: 100 }).filter((s) => s.trim().length > 0), { minLength: 2, maxLength: 5 }),
  complexity: fc.constantFrom('Low' as const, 'Medium' as const, 'High' as const),
});

/** Generates non-empty relaxation suggestion strings. */
const relaxationSuggestionsArb = fc.array(
  fc.string({ minLength: 1, maxLength: 200 }).filter((s) => s.trim().length > 0),
  { minLength: 1, maxLength: 5 },
);

/** Generates a list of constraint strings (at least 1 constraint to trigger restrictive scenario). */
const fallbackConstraintsArb = fc.array(
  fc.string({ minLength: 1, maxLength: 100 }).filter((s) => s.trim().length > 0),
  { minLength: 1, maxLength: 5 },
);

/** Generates a minimal Message array for the function input. */
const messageArbP28: fc.Arbitrary<Message> = fc.record({
  messageId: fc.uuid().map((id) => id as MessageId),
  threadId: fc.uuid().map((id) => id as ThreadId),
  sender: fc.constantFrom('user-1', 'ai_architect'),
  content: fc.string({ minLength: 1, maxLength: 200 }),
  createdAt: fc.date({ min: new Date('2024-01-01'), max: new Date('2025-01-01') }).map((d) => d.toISOString()),
});

describe('Property 28: Single-option fallback with relaxation suggestions', () => {
  beforeEach(() => {
    mockInvokeClaudeModel.mockReset();
  });

  it('when constraints produce only one viable option, returns single_option with valid structure and non-empty relaxationSuggestions', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.array(messageArbP28, { minLength: 1, maxLength: 3 }),
        fallbackConstraintsArb,
        singleOptionArb,
        relaxationSuggestionsArb,
        async (messages, constraints, generatedOption, generatedSuggestions) => {
          mockInvokeClaudeModel.mockReset();

          let callCount = 0;

          // Mock invokeClaudeModel:
          // First call: proposeOptions returns JSON with only 1 option (fails 2-5 validation)
          // Second call: generateRelaxationSuggestions returns relaxation suggestions array
          mockInvokeClaudeModel.mockImplementation(async () => {
            callCount++;
            if (callCount === 1) {
              // Return a proposal with only 1 option — triggers validation failure in proposeOptions
              const singleOptionResponse = JSON.stringify({
                options: [generatedOption],
                tradeoffTable: {
                  options: [generatedOption.summary.slice(0, 50) || 'Option A'],
                  constraints: constraints,
                  ratings: [constraints.map(() => 'Good')],
                },
              });
              return { ok: true, value: singleOptionResponse };
            }
            // Second call: return relaxation suggestions
            return { ok: true, value: JSON.stringify(generatedSuggestions) };
          });

          const result = await proposeOptionsWithFallback({
            messages,
            constraints,
            priorDecisions: [],
          });

          // Must succeed
          expect(result.ok).toBe(true);
          if (!result.ok) return;

          const proposalResult = result.value;

          // Must be single_option kind
          expect(proposalResult.kind).toBe('single_option');
          if (proposalResult.kind !== 'single_option') return;

          // Validate option structure
          const option = proposalResult.option;

          // summary ≤ 200 chars and non-empty
          expect(option.summary.length).toBeLessThanOrEqual(200);
          expect(option.summary.length).toBeGreaterThan(0);

          // ≥ 2 benefits, each non-empty
          expect(option.benefits.length).toBeGreaterThanOrEqual(2);
          option.benefits.forEach((b) => expect(b.length).toBeGreaterThan(0));

          // ≥ 2 risks, each non-empty
          expect(option.risks.length).toBeGreaterThanOrEqual(2);
          option.risks.forEach((r) => expect(r.length).toBeGreaterThan(0));

          // complexity in {Low, Medium, High}
          expect(['Low', 'Medium', 'High']).toContain(option.complexity);

          // relaxationSuggestions is non-empty array of non-empty strings
          expect(Array.isArray(proposalResult.relaxationSuggestions)).toBe(true);
          expect(proposalResult.relaxationSuggestions.length).toBeGreaterThan(0);
          proposalResult.relaxationSuggestions.forEach((s) => {
            expect(typeof s).toBe('string');
            expect(s.length).toBeGreaterThan(0);
          });
        },
      ),
      { numRuns: 50 },
    );
  });
});
